from setuptools import setup

setup(
    name='frameduster',
    version='1.0',
    description='A python package for enhanced deeplearning classification networks',
    url='https://github.com/shuds13/pyexample',
    author='X Team',
    author_email='luc.buysse@polytechnique.edu',
    license='MIT',
    packages=['frameduster'],
    install_requires=['torch==2.0.1',
                      'torchvision',
                      'numpy',
                      'pillow~=9.5.0',
                      'scikit-learn==1.2.2',
                      'tensorboard==2.13.0',
                      'ptwt',
                      'Pywavelets',
                      'loguru==0.7.0',
                      'tqdm==4.65.0',
                      'requests~=2.31.0',
                      'lxml~=4.9.2',
                      'PyYAML~=6.0',
                      'aioboto3==11.2.0',
                      'boto3==1.26.76',
                      'botocore~=1.29.76',
                      'motor==3.2.0',
                      'pymongo==4.4.1'],

    classifiers=[
        'Development Status :: 1 - Planning',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: BSD License',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
    ],
)